export const products = [
  {
    id: 1,
    slug: "no-pull-harness",
    emoji: "🐕",
    category: "dogs",
    nameFr: "Harnais anti-traction",
    nameEn: "No-pull harness",
    descriptionFr: "Un harnais confortable pensé pour mieux répartir la pression et rendre les promenades plus agréables.",
    descriptionEn: "A comfortable harness designed to distribute pressure and make walks more enjoyable.",
    price: 29.90,
  },
  {
    id: 2,
    slug: "retractable-leash",
    emoji: "🦮",
    category: "dogs",
    nameFr: "Laisse rétractable 5 m",
    nameEn: "5 m retractable leash",
    descriptionFr: "Une laisse pratique pour offrir plus de liberté à votre chien tout en gardant le contrôle.",
    descriptionEn: "A practical leash that gives your dog more freedom while keeping you in control.",
    price: 19.90,
  },
  {
    id: 3,
    slug: "portable-water-bottle",
    emoji: "💧",
    category: "dogs",
    nameFr: "Gourde portable 2-en-1",
    nameEn: "2-in-1 portable water bottle",
    descriptionFr: "Une gourde compacte pour hydrater facilement votre compagnon pendant les promenades et voyages.",
    descriptionEn: "A compact bottle that makes hydration easy during walks and trips.",
    price: 16.90,
  },
  {
    id: 4,
    slug: "lick-mat",
    emoji: "🐶",
    category: "dogs",
    nameFr: "Tapis de léchage anti-stress",
    nameEn: "Anti-stress lick mat",
    descriptionFr: "Un tapis texturé conçu pour occuper votre chien et ralentir la prise de nourriture.",
    descriptionEn: "A textured mat designed to keep your dog occupied and slow down feeding.",
    price: 12.90,
  },
  {
    id: 5,
    slug: "water-fountain",
    emoji: "🐈",
    category: "cats",
    nameFr: "Fontaine à eau silencieuse",
    nameEn: "Quiet water fountain",
    descriptionFr: "Une fontaine pensée pour encourager votre chat à boire régulièrement avec un fonctionnement discret.",
    descriptionEn: "A quiet fountain designed to encourage your cat to drink more regularly.",
    price: 34.90,
  },
  {
    id: 6,
    slug: "interactive-toy",
    emoji: "🎾",
    category: "cats",
    nameFr: "Jouet interactif",
    nameEn: "Interactive toy",
    descriptionFr: "Un jouet stimulant pour divertir les chats et encourager leur activité quotidienne.",
    descriptionEn: "A stimulating toy designed to entertain cats and encourage daily activity.",
    price: 18.90,
  },
  {
    id: 7,
    slug: "window-hammock",
    emoji: "🐱",
    category: "cats",
    nameFr: "Hamac de fenêtre",
    nameEn: "Window hammock",
    descriptionFr: "Un espace confortable en hauteur pour permettre à votre chat de se reposer et observer l'extérieur.",
    descriptionEn: "A comfortable elevated resting spot where your cat can relax and watch the world outside.",
    price: 24.90,
  },
  {
    id: 8,
    slug: "pet-brush",
    emoji: "🪮",
    category: "cats",
    nameFr: "Brosse anti-poils",
    nameEn: "Pet grooming brush",
    descriptionFr: "Une brosse pratique pour retirer les poils morts et entretenir le pelage en douceur.",
    descriptionEn: "A practical grooming brush for removing loose fur and maintaining a healthy coat.",
    price: 13.90,
  },
];
